app = "foxhole-logger"
primary_region = "iad" # change to your closest Fly.io region

[build]
  image = "Dockerfile"

[mounts]
  source = "foxhole_data"
  destination = "/data"

[env]
  PYTHONUNBUFFERED = "TRUE"

[processes]
  app = "sh -c 'python event_logger.py & python casualty_logger.py'"

[experimental]
  auto_rollback = true

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
