app = "foxhole-logger"
primary_region = "sjc"  # Or your closest Fly.io region

[build]
  image = "python:3.10-slim"  # You can change to 3.8 if required

[env]
  PYTHONUNBUFFERED = "1"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
