app = "foxhole-logger"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[mounts]
  source = "foxhole_data"
  destination = "/data"

[env]
  PYTHONUNBUFFERED = "TRUE"

[processes]
  app = "sh -c 'python foxhole_event_logger.py & python foxhole_casualty_logger.py'"
